### ISSUE TITLE
Typescript interface export support

### ISSUE THREAD

**Issue by joachim-heck** [KY-Programming/generator#1]
Hey Kai, first of all many thanks for providing such a nice c# to typescript generator. During use, I noticed that interfaces, applied to a specific class, are consequently ignored during export / generation. Is this the intended behaviour or maybe a feature for an upcoming release?
Thanks and greets!

**Comment by ky-one** [comment]
Hi Joachim,
good point. I implemented it for base classes but not for interfaces.
I try to get put it in the next release.
Regards Kai
