### ISSUE TITLE
Assemblies with '-' in name not found during generation

### ISSUE THREAD

**Issue by joachim-heck** [KY-Programming/generator#12]
Seems like generator is struggeling with special cases like "-" in the assembly name duing export. We are using protobuffer with the .net protobuf-net extension ("protobuf-net.dll")  in our projects. 

During Typescript / angular generation we receive some errors stating that KY.Generator isn't able to lookup the `"-net.dll"` file at the target folder, although the correct referred name is `protobuf-net.dll`. The process runs perfectly when we manually provide the assembly name in the `load` statement of the generator.json config

```
  "load": [
    "..\\..\\packages\\protobuf-net.2.4.0\\lib\\netcoreapp2.1\\protobuf-net.dll"
  ],
```

**Comment by ky-one** [comment]
Will be part of the 3.6.0 release
