### ISSUE TITLE
Ignore Property during generation attribute

### ISSUE THREAD

**Issue by joachim-heck** [KY-Programming/generator#13]
I've just discovered the ` [KY.Generator.Reflection.GenerateIgnore]` attribute which is perfectly usable to ignore certain classes from the generation process. I wonder if there is also an attribute which enables us to ignore certain properties from generation - like NewtonsoftJson does provide with `[JsonIgnore]`.

It would be awesome if you can extend the attributes, hence this would save us a lot of extra work wrapping out the unwanted properties.

Thanks and regards!

**Comment by ky-one** [comment]
Will be part of the 3.6.0 release
