### ISSUE TITLE
Could not load file or assembly exception on x86 build configurations

### ISSUE THREAD

**Issue by joachim-heck** [KY-Programming/generator#14]
Hey Kai, seems like I just stumbled over a bit of a special issue. In order to run some of our services on 32bit systems I need to switch the build configuration to x86 during build / publish... Unfortunately the Generator is crashing with a build error when trying to load the target specific built assemblies.

Is there a way to support x64 and x86 projects, or maybe switch off the Generator for specific build or publish configurations?

**Comment by ky-one** [comment]
Fixed with [v4.3.0](https://github.com/KY-Programming/generator/releases/tag/4.3.0)
