### ISSUE TITLE
GenerateAngularModel Attribute on multiple class definitions with different targets get messed up

### ISSUE THREAD

**Issue by joachim-heck** [KY-Programming/generator#16]
Hey Kai - first of all, congrats to that gorgeous new version 5 you've just released. 
There is only one bugfix away from beeing perfect ;-) I just figured out that the generator is struggeling having multiple build definitions targeting different output folders.

My setup contains 2 classes which are targeting two output folders:

```  
[KY.Generator.GenerateAngularModel("..\\..\\..\\my-site\\module1\\api-models")]
public class GeneratorModule1
{
  public SubClass1 MySubclass1{ get; set; }
  public SubClass2 MySubclass2{ get; set; }
  public SubClass3 MySubclass3{ get; set; }
}
```  

```  
[KY.Generator.GenerateAngularModel("..\\..\\..\\my-site\\module2\\api-models")]
public class GeneratorModule2
{
  public SubClass4 MySubclass4{ get; set; }
  public SubClass5 MySubclass5{ get; set; }
  public SubClass6 MySubclass6{ get; set; }
}
```  

It seems like generator is mixing up both definitions and generates all files in both target folders.
Can you confirm that behaviour or have i misconfigured something?

Thanks and greetings!

**Comment by ky-one** [comment]
Fixed with the next release
