### ISSUE TITLE
Ignore generic from controller return type / result

### ISSUE THREAD

**Issue by joachim-heck** [KY-Programming/generator#20]
I think it would be a great extension to make the generator ignore some custom return types of the controllers.
In my case our angular `HttpInterceptor` is handling some HttpHeader data from the `CustomResponse` and then only throughputs the inner `TestData` Object ... the service wrapper for the endpoint therefore must ignore the `CustomResponse` type.

```
        [HttpGet, Route("testendpoint")]
        public CustomResponse<TestData> GetTestData()
        {
            return this.GetTestData();
        }

```

Like you already ignore the `Task`-type in:

https://github.com/KY-Programming/generator/blob/5be6e6ac94b79a5bf0ab3654982e6d5bc5c28410/AspDotNet/Readers/AspDotNetControllerReader.cs#L46

**Comment by ky-one** [comment]
Added [GenerateIgnoreGenericAttribute](http://generator.ky-programming.de/reflection/overview/api#GenerateIgnoreGenericAttribute)

Will be part of the next release
