### ISSUE TITLE
Constants export feature / default value attribute?

### ISSUE THREAD

**Issue by joachim-heck** [KY-Programming/generator#26]
Hey Kai, thanks for the great updates - I wonder if there is any way to export constants aswell?

for example: 
```
public class MyConstantsRegister {
   public const string Constant1 = "my constant 1";
   public const string Constant2 = "my constant 2";
   ...
}
```

Currently this is not possible, due to you are only watching for properties - but maybe there is any workaround?
Probably with an option to specify a default value via Attribute or Fluent language?
```
public class MyConstantsRegister {
   [KY.PropertyDefaultValue("my constant 1")]
   public string Constant1 {get;set;}
   [KY.PropertyDefaultValue("my constant 2")]
   public string Constant2 = "myconstant 2"
   ...
}
```

What do you think?

**Comment by ky-one** [comment]
Hi Joachim,
i am not sure if this is possible, but i will try it.

**Comment by ky-one** [comment]
Hi Joachim,
with version 6.3.0 all public constants are exported with its default value

**Comment by joachim-heck** [comment]
Whooohoo, this is a really nice feature - Thanks!
Now the signalR message names are in sync too ;-)
