### ISSUE TITLE
Additional line breaks on linux build

### ISSUE THREAD

**Issue by joachim-heck** [KY-Programming/generator#27]
Hey Kai, we are building our api-models and -services on windows and linux machines parallely and discovered a small bug on the header comment section of the generated file. Seems like there are some additional lines on the linux generated files (LEFT) compared to the windows generated file (RIGHT)

![image](https://user-images.githubusercontent.com/49340614/105336504-9e7daf80-5bd9-11eb-89a2-b05f439fa59f.png)

**Comment by ky-one** [comment]
Fixed. Will be part of the next release
