### ISSUE TITLE
ApiController generator fails when using custom Produces attribute

### ISSUE THREAD

**Issue by joachim-heck** [KY-Programming/generator#32]
Hey Kai, we just realized a minor bug during generation of our api endpoints - seems like the generator isn't able to handle custom [Produces("CUSTOM_TYPE")] attributes. Is it a bug, or a feature?

**Comment by ky-one** [comment]
The exception comes from .NET Framework, because you have to use the attribute like this:
`[Produces("application/json")]`
or
`[Produces(typeof(CustomType))]`
