### ISSUE TITLE
.net 6  support

### ISSUE THREAD

**Issue by joachim-heck** [KY-Programming/generator#46]
Hello KY, are you planning to officially support .net 6.0 soon? Currently the generator can be tricked doing so by an additional entry in the Generator.targets...

![image](https://user-images.githubusercontent.com/49340614/146407872-8993f34b-beb0-461e-838c-ba942f2570b3.png)

**Comment by ky-one** [comment]
.net 6 will be supported with v8.2 (coming soon)
