### ISSUE TITLE
Missing KY.Generator.GenerateAngularIndex 

### ISSUE THREAD

**Issue by joachim-heck** [KY-Programming/generator#47]
Seems like the 8.1 version is missing my beloved `GenerateAngularIndex` attribute and the `[KY.Generator.GenerateIndex(OutputLanguage.TypeScript,...` doesn't seem to be the right replacement. Am I missing out something?

**Comment by ky-one** [comment]
The v8 replaces `[GenerateIndex]` with `[GenerateAngularModel(...), GenerateOnlySubTypes]`
GenerateIndex was no good name because it was not clear what it does and it had no relation to Angular.

[See documentation](https://generator.ky-programming.de/v8/angular/model/special-cases/via-annotations)
