### ISSUE TITLE
Typescript customType[] array support

### ISSUE THREAD

**Issue by joachim-heck** [KY-Programming/generator#5]
Hey Kai, still a pleasure to use your generator - will the next update also support the the array datatype for custom type definitions? Currently custom typed (FooType) properties marked as array are exported kind of inconsistent:

```
public class FooClass {
   public string[] fooArray1 { get; set; }  
   public FooType[] fooArray2 { get; set; }  
   public List<FooListType> fooList { get; set; }  
}
```

currently gets exported as

```
import { FooType[] } from "./foo-type[]";  
import { FooListType } from "./foo-list-type";  

export class FooClass {  
    public fooArray1: string[];
    public fooArray2: FooType[];
    public fooList: FooListType[];
}
```

Thanks and regards
Joachim

**Comment by ky-one** [comment]
Fixed in nearly done v2.0.0
