### ISSUE TITLE
Typescript nested types support

### ISSUE THREAD

**Issue by joachim-heck** [KY-Programming/generator#6]
Hey Kai, still tweaking on the limits of your fantastic generator - I'm facing the scenario where I'm nesting the exported class within the class itself, which leads to an unnecessary import of the nested class:

Exported file: `my-class.ts`

```
import { MyClass } from "./my-class";

export class MyClass {
    public children: MyClass[];
}

```

> error TS2395: Individual declarations in merged declaration 'MyClass ' must be all exported or all local.

Regards and keep up the great work!
Joachim

**Comment by ky-one** [comment]
Fixed in nearly done v2.0.0
