### ISSUE TITLE
GenericType<T> of double not resolved correctly

### ISSUE THREAD

**Issue by joachim-heck** [KY-Programming/generator#9]
Hey Kai, 

first of all: thanks for the magnificent support! I'm referring the issue you have fixed in your last update https://github.com/KY-Programming/generator/issues/8; It seems like the complex scenarios are now working like charm but in my case, its probably struggeling with some base types:

I'm reusing that generic type of #8 

```
public class GenericType<T>
 {
     public int Value1 { get; set; }

     public T GenericValue { get; set; }

 }
```

but this time I'm feeding it a double-Value as Input:
```

public class ExportedType
{
    public GenericType<double> MyType { get; set; }
}
```

As a result, the GenericType class gets perfectly generated, but in the Exported type the T is not getting resolved:

```
import { GenericType } from "./generic-type";

export class ExportedType {
 public myType: GenericType<>;

 public constructor(init: Partial<ExportedType> = undefined) {
     Object.assign(this, init);
 }
}
```

**Comment by ky-one** [comment]
Solved. Will be part of the next release
